### ISSUE TITLE
Cannot read property posts of undefined

### ISSUE THREAD

**Issue by thany** [yocontra/4chanjs#5]
I'm getting this error consistently:
```
d:\Projecten\Chanatica\node_modules\4chanjs\index.js:70
      cb(null, body.posts);
                   ^

TypeError: Cannot read property 'posts' of undefined
    at Request._callback (d:\Projecten\Chanatica\node_modules\4chanjs\index.js:70:20)
    at Request.self.callback (d:\Projecten\Chanatica\node_modules\request\request.js:186:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (d:\Projecten\Chanatica\node_modules\request\request.js:1163:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (d:\Projecten\Chanatica\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
```

At line 70 when it breaks on this exception:
`err` = `null`
`res` = a 404 or 304 response object
`body` = `undefined`

Weirdly, when I look at `this` and get the request url, if I execute that from within a normal browser, I get a totally fine json response. So why is it returning a 404 response to 4chanjs, I have no idea. And why err is null even though there's an error, I have no idea. But I was hoping this can be fixed anyway :)

The really curious one is when 4chan manages to return a **304** response, which in theory could only have come from a request with an If-Modified-Since header. And whaddayaknow, the request does include such header - but why? How does 4chanjs know (or think it knows) what's been fetched before? Does it keep track of previous requests *across sessions*? Surely not, right?

Mind you, this issue is not reproducible on demand. It happens incidentally.

**Comment by thany** [comment]
Small followup, I just noticed this in the source:

```javascript
  headers: {
    'if-modified-since': (new Date()).toUTCString()
  }
```
What's that for? Why must the If-Modified-Since header be set to *now*? What if it hasn't changed but I still want the file?...
